import { legacyStage } from './stages';
import { MAPS } from './data';
import { DUNGEONS, MANUALS } from './expansion';
import type { GameState } from './types';

export type TitleRarity = 'rare' | 'epic' | 'legendary' | 'mythic' | 'supreme';
export type TitleEffect = 'mist' | 'flame' | 'lightning' | 'frost' | 'stars' | 'chaos';
export type TitleAttribute = 'attack' | 'defense' | 'health' | 'cultivation' | 'crit';
export interface CultivationTitle {
  id: string;
  name: string;
  symbol: string;
  rarity: TitleRarity;
  effect: TitleEffect;
  attribute: TitleAttribute;
  bonus: number;
  requirement: string;
  target: number;
  progress: (s: GameState) => number;
}
export const TITLE_RARITIES: Record<TitleRarity, string> = {
  rare: 'Hiếm',
  epic: 'Sử thi',
  legendary: 'Truyền thuyết',
  mythic: 'Thần thoại',
  supreme: 'Chí tôn',
};
export const TITLE_EFFECTS: Record<TitleEffect, string> = {
  mist: 'Thanh vân lưu chuyển',
  flame: 'Hỏa diễm bùng cháy',
  lightning: 'Lôi quang phá không',
  frost: 'Băng liên kết tinh',
  stars: 'Tinh hà xoay chuyển',
  chaos: 'Hồng mông đạo vận',
};
export const TITLE_ATTRIBUTES: Record<TitleAttribute, string> = {
  attack: 'công kích',
  defense: 'phòng thủ',
  health: 'sinh lực',
  cultivation: 'hiệu quả thiền',
  crit: 'tỷ lệ chí mạng',
};
const title = (
  id: string,
  name: string,
  symbol: string,
  rarity: TitleRarity,
  effect: TitleEffect,
  attribute: TitleAttribute,
  bonus: number,
  requirement: string,
  target: number,
  progress: (s: GameState) => number,
): CultivationTitle => ({
  id,
  name,
  symbol,
  rarity,
  effect,
  attribute,
  bonus,
  requirement,
  target,
  progress,
});
const worldMaps = (s: GameState, world: string) =>
  MAPS.filter((m) => m.world === world && s.explored.includes(m.id)).length;
const clears = (s: GameState) =>
  Object.values(s.dungeons.clears).reduce((n, count) => n + count, 0);
const mastered = (s: GameState) => Object.values(s.manuals).reduce((n, level) => n + level, 0);
const minutes = (s: GameState) => Math.floor(s.training.totalSeconds / 60);

export const TITLES: CultivationTitle[] = [
  title(
    'realm-foundation',
    'Trúc Cơ Đạo Chủ',
    '道',
    'rare',
    'mist',
    'health',
    0.04,
    'Đạt Trúc Cơ Sơ kỳ',
    4,
    (s) => s.stage,
  ),
  title(
    'realm-golden',
    'Kim Đan Chân Nhân',
    '丹',
    'epic',
    'flame',
    'cultivation',
    0.05,
    'Đạt Kim Đan Sơ kỳ',
    8,
    (s) => s.stage,
  ),
  title(
    'realm-soul',
    'Nguyên Anh Thiên Quân',
    '魂',
    'epic',
    'frost',
    'defense',
    0.06,
    'Đạt Nguyên Anh Sơ kỳ',
    12,
    (s) => s.stage,
  ),
  title(
    'realm-spirit',
    'Hóa Thần Tôn Giả',
    '神',
    'legendary',
    'lightning',
    'attack',
    0.07,
    'Đạt Hóa Thần Sơ kỳ',
    16,
    (s) => s.stage,
  ),
  title(
    'realm-mahayana',
    'Đại Thừa Đạo Tôn',
    '玄',
    'legendary',
    'mist',
    'cultivation',
    0.08,
    'Đạt Đại Thừa Sơ kỳ',
    28,
    (s) => s.stage,
  ),
  title(
    'realm-immortal',
    'Cửu Thiên Chân Tiên',
    '仙',
    'mythic',
    'stars',
    'health',
    0.1,
    'Đạt Chân Tiên Sơ kỳ',
    36,
    (s) => s.stage,
  ),
  title(
    'realm-taiyi',
    'Thái Ất Kiếm Tiên',
    '劍',
    'mythic',
    'lightning',
    'attack',
    0.1,
    'Đạt Thái Ất Sơ kỳ',
    48,
    (s) => s.stage,
  ),
  title(
    'realm-emperor',
    'Vạn Cổ Tiên Đế',
    '帝',
    'mythic',
    'flame',
    'defense',
    0.12,
    'Đạt Tiên Đế Sơ kỳ',
    60,
    (s) => s.stage,
  ),
  title(
    'realm-divine',
    'Chư Thiên Thần Chủ',
    '天',
    'supreme',
    'stars',
    'cultivation',
    0.12,
    'Đạt Chân Thần Sơ kỳ',
    64,
    (s) => s.stage,
  ),
  title(
    'realm-origin',
    'Hồng Mông Thần Đế',
    '鴻',
    'supreme',
    'chaos',
    'health',
    0.18,
    'Đạt Thần Đế Đỉnh phong',
    79,
    (s) => s.stage,
  ),

  title(
    'kill-first',
    'Nhất Kiếm Khai Thiên',
    '劍',
    'rare',
    'lightning',
    'attack',
    0.03,
    'Thắng 1 trận trừ yêu',
    1,
    (s) => s.metrics.kills,
  ),
  title(
    'kill-ten',
    'Trảm Yêu Đạo Nhân',
    '斬',
    'rare',
    'mist',
    'defense',
    0.04,
    'Thắng 10 trận trừ yêu',
    10,
    (s) => s.metrics.kills,
  ),
  title(
    'kill-fifty',
    'Bách Chiến Kiếm Tâm',
    '心',
    'epic',
    'flame',
    'attack',
    0.05,
    'Thắng 50 trận trừ yêu',
    50,
    (s) => s.metrics.kills,
  ),
  title(
    'kill-twohundred',
    'Vạn Kiếm Quy Tông',
    '宗',
    'legendary',
    'lightning',
    'crit',
    0.02,
    'Thắng 200 trận trừ yêu',
    200,
    (s) => s.metrics.kills,
  ),
  title(
    'kill-fivehundred',
    'Sát Thần Vô Song',
    '殺',
    'mythic',
    'flame',
    'attack',
    0.1,
    'Thắng 500 trận trừ yêu',
    500,
    (s) => s.metrics.kills,
  ),
  title(
    'elite-ten',
    'Yêu Vương Khắc Tinh',
    '王',
    'legendary',
    'frost',
    'defense',
    0.08,
    'Hạ 10 quái tinh anh',
    10,
    (s) => s.encounters.eliteKills,
  ),
  title(
    'boss-secrets',
    'Tam Giới Tru Ma',
    '魔',
    'supreme',
    'chaos',
    'crit',
    0.04,
    'Hạ cả 3 boss ẩn',
    3,
    (s) => s.encounters.defeatedBosses.length,
  ),

  title(
    'training-ten',
    'Nhất Niệm Nhập Đạo',
    '悟',
    'rare',
    'mist',
    'cultivation',
    0.03,
    'Ngồi thiền tổng cộng 10 phút',
    10,
    minutes,
  ),
  title(
    'training-hour',
    'Tâm Tĩnh Như Thủy',
    '水',
    'rare',
    'frost',
    'health',
    0.04,
    'Ngồi thiền tổng cộng 60 phút',
    60,
    minutes,
  ),
  title(
    'training-fivehours',
    'Thanh Tâm Vô Trần',
    '清',
    'epic',
    'mist',
    'defense',
    0.06,
    'Ngồi thiền tổng cộng 300 phút',
    300,
    minutes,
  ),
  title(
    'training-tenhours',
    'Đạo Tâm Bất Diệt',
    '道',
    'legendary',
    'flame',
    'cultivation',
    0.08,
    'Ngồi thiền tổng cộng 600 phút',
    600,
    minutes,
  ),
  title(
    'training-thirtyhours',
    'Vạn Pháp Quy Nhất',
    '法',
    'mythic',
    'stars',
    'cultivation',
    0.1,
    'Ngồi thiền tổng cộng 1.800 phút',
    1800,
    minutes,
  ),
  title(
    'training-sixtyhours',
    'Nhất Niệm Vĩnh Hằng',
    '永',
    'supreme',
    'chaos',
    'cultivation',
    0.15,
    'Ngồi thiền tổng cộng 3.600 phút',
    3600,
    minutes,
  ),

  title(
    'explore-ten',
    'Tiêu Dao Du Tử',
    '遊',
    'rare',
    'mist',
    'health',
    0.03,
    'Xuất hành 10 lần',
    10,
    (s) => s.metrics.explorations,
  ),
  title(
    'explore-fifty',
    'Ngự Phong Vạn Dặm',
    '風',
    'epic',
    'lightning',
    'crit',
    0.01,
    'Xuất hành 50 lần',
    50,
    (s) => s.metrics.explorations,
  ),
  title(
    'earth-cartographer',
    'Địa Giới Thiên Hành',
    '地',
    'epic',
    'flame',
    'attack',
    0.06,
    'Đặt chân đến đủ 9 map Địa giới',
    9,
    (s) => worldMaps(s, 'earth'),
  ),
  title(
    'immortal-cartographer',
    'Cửu Thiên Vân Du',
    '雲',
    'legendary',
    'mist',
    'cultivation',
    0.08,
    'Đặt chân đến đủ 9 map Tiên giới',
    9,
    (s) => worldMaps(s, 'immortal'),
  ),
  title(
    'divine-cartographer',
    'Tinh Hà Lữ Khách',
    '星',
    'mythic',
    'stars',
    'health',
    0.12,
    'Đặt chân đến đủ 9 map Thần giới',
    9,
    (s) => worldMaps(s, 'divine'),
  ),
  title(
    'all-cartographer',
    'Vạn Giới Độc Hành',
    '界',
    'supreme',
    'chaos',
    'defense',
    0.12,
    'Đặt chân đến đủ 27 map',
    27,
    (s) => s.explored.length,
  ),

  title(
    'manual-three',
    'Tàng Kinh Đạo Sĩ',
    '書',
    'rare',
    'mist',
    'cultivation',
    0.04,
    'Học 3 bí kíp khác nhau',
    3,
    (s) => Object.keys(s.manuals).length,
  ),
  title(
    'manual-eight',
    'Bát Hoang Pháp Chủ',
    '法',
    'epic',
    'lightning',
    'attack',
    0.06,
    'Học 8 bí kíp khác nhau',
    8,
    (s) => Object.keys(s.manuals).length,
  ),
  title(
    'manual-all',
    'Vạn Pháp Thiên Tôn',
    '尊',
    'mythic',
    'stars',
    'cultivation',
    0.1,
    'Học đủ 15 bí kíp',
    MANUALS.length,
    (s) => Object.keys(s.manuals).length,
  ),
  title(
    'manual-breath',
    'Quy Nguyên Chân Quân',
    '元',
    'legendary',
    'frost',
    'health',
    0.08,
    'Đưa Dẫn Khí Quyết đến tầng 10',
    10,
    (s) => s.manuals.breath || 0,
  ),
  title(
    'manual-hundred',
    'Thiên Đạo Diễn Pháp',
    '衍',
    'supreme',
    'chaos',
    'attack',
    0.12,
    'Tổng tầng bí kíp đạt 100',
    100,
    mastered,
  ),

  title(
    'root-five',
    'Thiên Tư Tuyệt Thế',
    '靈',
    'epic',
    'frost',
    'cultivation',
    0.05,
    'Tẩy luyện linh căn đến cấp 5',
    5,
    (s) => s.spiritualRoot?.level || 0,
  ),
  title(
    'root-ten',
    'Tiên Thiên Đạo Thể',
    '體',
    'mythic',
    'stars',
    'health',
    0.12,
    'Tẩy luyện linh căn đến cấp 10',
    10,
    (s) => s.spiritualRoot?.level || 0,
  ),
  title(
    'legacy-three',
    'Cổ Đạo Truyền Nhân',
    '古',
    'legendary',
    'flame',
    'attack',
    0.08,
    'Nhận 3 truyền thừa',
    3,
    (s) => s.inheritances.length,
  ),
  title(
    'legacy-all',
    'Thái Sơ Kế Đạo',
    '始',
    'supreme',
    'chaos',
    'cultivation',
    0.14,
    'Nhận đủ 9 truyền thừa',
    9,
    (s) => s.inheritances.length,
  ),

  title(
    'sect-disciple',
    'Tiên Môn Chân Truyền',
    '門',
    'rare',
    'mist',
    'defense',
    0.04,
    'Tích lũy 250 cống hiến trong tông môn',
    250,
    (s) => (s.sect ? s.contribution : 0),
  ),
  title(
    'sect-founder',
    'Khai Sơn Tổ Sư',
    '祖',
    'epic',
    'flame',
    'health',
    0.06,
    'Tự khai sơn lập phái',
    1,
    (s) => (s.customSect ? 1 : 0),
  ),
  title(
    'sect-five',
    'Nhất Tông Chi Chủ',
    '主',
    'legendary',
    'lightning',
    'attack',
    0.08,
    'Nâng tông môn tự lập đến cấp 5',
    5,
    (s) => s.customSect?.level || 0,
  ),
  title(
    'sect-ten',
    'Vạn Cổ Đạo Thống',
    '統',
    'supreme',
    'chaos',
    'health',
    0.15,
    'Nâng tông môn tự lập đến cấp 10',
    10,
    (s) => s.customSect?.level || 0,
  ),

  title(
    'dungeon-first',
    'Phá Trận Tiên Phong',
    '陣',
    'rare',
    'lightning',
    'attack',
    0.04,
    'Vượt 1 phó bản',
    1,
    clears,
  ),
  title(
    'dungeon-ten',
    'Cửu U Chiến Thần',
    '戰',
    'legendary',
    'flame',
    'crit',
    0.02,
    'Vượt phó bản tổng cộng 10 lần',
    10,
    clears,
  ),
  title(
    'dungeon-all',
    'Chư Thiên Phá Kiếp',
    '劫',
    'supreme',
    'stars',
    'defense',
    0.12,
    'Vượt cả 9 phó bản khác nhau',
    DUNGEONS.length,
    (s) => Object.keys(s.dungeons.clears).filter((id) => s.dungeons.clears[id] > 0).length,
  ),

  title(
    'craft-first',
    'Linh Hỏa Đan Sư',
    '火',
    'rare',
    'flame',
    'health',
    0.03,
    'Luyện chế thành công 1 lần',
    1,
    (s) => s.metrics.crafts,
  ),
  title(
    'craft-fifty',
    'Cửu Chuyển Đan Tôn',
    '丹',
    'legendary',
    'flame',
    'cultivation',
    0.07,
    'Luyện chế thành công 50 lần',
    50,
    (s) => s.metrics.crafts,
  ),
  title(
    'divine-wealth',
    'Thần Tài Tam Giới',
    '財',
    'mythic',
    'stars',
    'health',
    0.1,
    'Sở hữu cùng lúc 100 thần thạch',
    100,
    (s) => s.wallet.divine,
  ),

  title(
    'npc-all',
    'Thiên Hạ Tri Kỷ',
    '緣',
    'epic',
    'frost',
    'defense',
    0.06,
    'Gặp đủ 20 NPC',
    20,
    (s) => s.npcMet.length,
  ),
  title(
    'worldboss-ten',
    'Chư Thiên Tru Thần',
    '誅',
    'supreme',
    'lightning',
    'attack',
    0.12,
    'Nhận thưởng boss thế giới 10 chu kỳ',
    10,
    (s) => s.worldBossClaims,
  ),
];

export const titleUnlocked = (s: GameState, t: CultivationTitle) =>
  s.titles.owned.includes(t.id) || t.progress(s) >= t.target;
export function collectTitles(s: GameState) {
  const earned = TITLES.filter((t) => !s.titles.owned.includes(t.id) && t.progress(s) >= t.target);
  s.titles.owned.push(...earned.map((t) => t.id));
  return earned;
}
export const equippedTitle = (s: GameState) =>
  TITLES.find((t) => t.id === s.titles.equipped && titleUnlocked(s, t));
export const titleBonusText = (t: CultivationTitle) =>
  `+${Math.round(t.bonus * 100)}${t.attribute === 'crit' ? ' điểm %' : '%'} ${TITLE_ATTRIBUTES[t.attribute]}`;
